Add some logging to the benchmark runner
We're seeing this error in the output on ruby-kai1 and need to identify
where it's coming from:

undefined method `split' for nil:NilClass (NoMethodError)